# Generated by Django 5.2 on 2025-05-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('accuracy', models.FloatField()),
                ('trained_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
